AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Description: "Deploys the metrics-server helm chart into an existing kubernetes cluster (qs-qwertyuiop)"
Parameters:
  EksClusterName:
    Type: String
Resources:
  MetricsServerHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: kube-system
      Chart: stable/metrics-server
      Values:
        image.repository: k8s.gcr.io/metrics-server-amd64
        image.tag: v0.3.6
        args:
        - --kubelet-preferred-address-types=InternalIP
        rbac.create: true
        rbac.pspEnabled: true
        podDisruptionBudget.enabled: true
        podDisruptionBudget.maxUnavailable: 0
Outputs:
  MetricsServerReleaseName:
    Value: !Ref MetricsServerHelmChart
