AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the EKS control plane (qs-1p7nknofn)"
Parameters:
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  RoleArn:
    Type: String
  NodeInstanceRoleArn:
    Type: String
  KubeManifestLambdaArn:
    Type: String
  KubeConfigUploadLambdaArn:
    Type: String
  KubeConfigUploadRoleArn:
    Type: String
  KubeConfigS3Bucket:
    Type: String
  KubeConfigS3Key:
    Type: String
    Default: ".kube/config.enc"
  KmsKeyArn:
    Type: String
  KmsContext:
    Type: String
    Default: "EKSQuickStart"
Resources:
  EKS:
    Type: "AWS::EKS::Cluster"
    Properties:
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      RoleArn: !Ref RoleArn
  EksNodeConfigMap:
    DependsOn: KubeConfigToS3
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeManifestLambdaArn
      KubeConfigPath: !Sub "s3://${KubeConfigS3Bucket}/${KubeConfigS3Key}"
      KubeConfigKmsContext: !Ref KmsContext
      Manifest:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: aws-auth
          namespace: kube-system
        data:
          mapRoles: !Sub |
            - rolearn: ${NodeInstanceRoleArn}
              username: system:node:{{EC2PrivateDNSName}}
              groups:
                - system:bootstrappers
                - system:nodes
  KubeConfigToS3:
    Type: "Custom::ConfigToS3"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeConfigUploadLambdaArn
      RoleArn: !Ref KubeConfigUploadRoleArn
      EKSCAData: !GetAtt EKS.CertificateAuthorityData
      EKSEndpoint: !GetAtt EKS.Endpoint
      EKSArn: !GetAtt EKS.Arn
      S3BucketName: !Ref KubeConfigS3Bucket
      S3Key: !Ref KubeConfigS3Key
      EncryptionContext: !Ref KmsContext
      KmsKeyArn: !Ref KmsKeyArn
Outputs:
  EksArn:
    Value: !GetAtt EKS.Arn
  CAData:
    Value: !GetAtt EKS.CertificateAuthorityData
  EKSEndpoint:
    Value: !GetAtt EKS.Endpoint
  EKSName:
    Value: !Ref EKS
  KubeConfigPath:
    Value: !Sub "s3://${KubeConfigS3Bucket}/${KubeConfigS3Key}"